# Generated by Django 5.2 on 2025-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
